### PR TITLE
feat: support for latest build settings

### PR DESCRIPTION
**Pull request by jscheid**
Examples from https://docs.docker.com/compose/compose-file/compose-file-v3/#build

### CODE REVIEW

**Comment by stephanbuys** [comment]
@jscheid I think this is an okay interim solution, so I will go ahead and publish this. However I think that ultimately environment variables are strings, so if I get time I will consider doing the necessary de-serialization work to convert these other types to strings. I'm not sure what the impact of this will be on other tools that might rely on the `String` type. So I will make this a minor version bump. Thanks for the contribution.

**Comment by jscheid** [comment]
@stephanbuys I think you meant for your comment to go on the other PR :-) 
If this lib could convert to string (in the same way that the go code does) that would be even better, definitely. Thanks!

**Comment by stephanbuys** [comment]
Hi, yeah I meant it for the other PR, thanks for both! :-) It is just a bit of a pain figuring out the `serde` intricacies, but it is 100% possible to de-serialize one type to another. Just a bit stretched for time to really investigate that at the moment. Either way your fixes will serialize into something that `docker-compose` will understand.

**Comment by jscheid** [comment]
No rush from my end, thanks for all you've done so far. I need it only for deserialization for now. Ultimately I'd like it to ingest any docker-compose file found in the wild (that the go code accepts), to that end there might be a few more small PRs coming because I think there are still some v3 constructs not yet recognized.

**Pull request merged**
